{% set version = "2.1" %}
{% set sha256 = "7e7e3324e2ea10c1748bb774c79f6bfb8ac92883956850bf3331abff01f79b6a" %}

package:
  name: argparse
  version: {{ version }}

source:
  url: https://github.com/p-ranav/argparse/archive/v{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.1
    - ninja
  host: []  # Empty host dependency section

test:
  commands:
    - test -f ${PREFIX}/include/argparse/argparse.hpp           # [unix]
    - test -f ${PREFIX}/lib/cmake/argparse/argparseConfig.cmake # [unix]
    - if exist %LIBRARY_PREFIX%\include\argparse\argparse.hpp (exit 0) else (exit 1)   # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\argparseConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/p-ranav/argparse
  license: MIT
  license_file: LICENSE
  summary: Argument Parser for Modern C++
  description: |
    Simply include argparse.hpp and you're good to go.

extra:
  recipe-maintainers:
    - zhihao.yuan
